"""
Shared helpers for the ftfy-js codegen scripts.

These scripts ``import ftfy`` from the upstream python-ftfy checkout and emit
byte-identical TypeScript data tables under ``src/generated/``. The parity
guarantee depends on this output being deterministic: sorted keys, no
locale/platform-dependent formatting, ASCII-only escaping, and LF newlines.

Environment:
    - The upstream python-ftfy source must be importable. By default we use the
      ``python-ftfy`` git submodule at the repository root; override with
      FTFY_PYTHON_SRC.
    - ftfy depends on ``wcwidth``. The recommended runner is ``uv`` — each script
      carries PEP 723 metadata (``requires-python = "==3.12.*"``,
      ``dependencies = ["wcwidth"]``), so ``uv run scripts/gen_all.py`` (a.k.a.
      ``npm run gen``) provisions wcwidth and pins Python 3.12 (→ unidata 15.0.0)
      with zero setup. As a fallback for bare ``python3``, wcwidth can be vendored
      into ``.pyenv`` at the repo root (``pip install --target .pyenv wcwidth``);
      this module puts it on sys.path automatically.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_DIR = REPO_ROOT / "src" / "generated"


def _python_ftfy_src() -> Path:
    override = os.environ.get("FTFY_PYTHON_SRC")
    if override:
        return Path(override).resolve()
    return (REPO_ROOT / "python-ftfy").resolve()


PYTHON_FTFY_SRC = _python_ftfy_src()


def _setup_sys_path() -> None:
    # Vendored third-party deps (e.g. wcwidth) first, so `import ftfy` succeeds.
    vendored = REPO_ROOT / ".pyenv"
    if vendored.is_dir():
        sys.path.insert(0, str(vendored))
    # The upstream python-ftfy package (the spec we port from).
    if not (PYTHON_FTFY_SRC / "ftfy").is_dir():
        raise SystemExit(
            f"codegen: upstream python-ftfy source not found at {PYTHON_FTFY_SRC}. "
            "Run `git submodule update --init python-ftfy` or set FTFY_PYTHON_SRC."
        )
    sys.path.insert(0, str(PYTHON_FTFY_SRC))


_setup_sys_path()


def upstream_commit() -> str:
    """Return the git commit SHA of the upstream python-ftfy checkout."""
    try:
        out = subprocess.run(
            ["git", "-C", str(PYTHON_FTFY_SRC), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip()
    except Exception:
        return "unknown"


# The Unicode version the committed tables are pinned to. CPython bundles a
# fixed unicodedata per minor version (3.12 -> 15.0.0), so running the codegen on
# a different Python can silently change the name/category tables. uv pins
# Python 3.12 via each script's PEP 723 `requires-python`; this is the belt-and-
# suspenders guard for the bare-`python3` path.
EXPECTED_UNIDATA_VERSION = "15.0.0"


def check_unidata_version() -> None:
    import unicodedata

    actual = unicodedata.unidata_version
    if actual != EXPECTED_UNIDATA_VERSION and not os.environ.get("FTFY_ALLOW_UNIDATA_DRIFT"):
        raise SystemExit(
            f"codegen: unicodedata.unidata_version is {actual}, expected "
            f"{EXPECTED_UNIDATA_VERSION}. Run under `uv run` (pins Python 3.12) or "
            f"set FTFY_ALLOW_UNIDATA_DRIFT=1 to regenerate against this version on "
            f"purpose (and update EXPECTED_UNIDATA_VERSION + the file headers)."
        )


def header(generator: str) -> str:
    """
    Build the deterministic banner that every generated file carries.

    It names the generator, the upstream ftfy version, the upstream commit SHA,
    and the Python ``unicodedata.unidata_version`` used to produce the tables.
    """
    import unicodedata

    import ftfy

    check_unidata_version()
    return (
        "// AUTO-GENERATED FILE — DO NOT EDIT.\n"
        "//\n"
        f"// Generated by scripts/{generator}\n"
        f"// Upstream: python-ftfy {ftfy.__version__} (commit {upstream_commit()})\n"
        f"// Python unicodedata.unidata_version: {unicodedata.unidata_version}\n"
        "//\n"
        "// Regenerate with `npm run gen` (uv run scripts/gen_all.py); CI asserts no git diff.\n"
        "// This is a faithful port of python-ftfy by Robyn Speer (Apache-2.0).\n"
        "\n"
    )


_SIMPLE_ESCAPES = {
    ord("\\"): "\\\\",
    ord('"'): '\\"',
    ord("\n"): "\\n",
    ord("\r"): "\\r",
    ord("\t"): "\\t",
}


def ts_string_literal(s: str) -> str:
    """
    Render ``s`` as an ASCII-only double-quoted TypeScript string literal whose
    runtime value equals ``s`` exactly.

    Every codepoint outside printable ASCII becomes a ``\\xHH`` / ``\\uHHHH`` /
    ``\\u{HHHHH}`` escape, so the emitted file is byte-stable regardless of the
    editor or filesystem encoding.
    """
    out = ['"']
    for ch in s:
        cp = ord(ch)
        if cp in _SIMPLE_ESCAPES:
            out.append(_SIMPLE_ESCAPES[cp])
        elif 0x20 <= cp <= 0x7E:
            out.append(ch)
        elif cp <= 0xFF:
            out.append(f"\\x{cp:02x}")
        elif cp <= 0xFFFF:
            out.append(f"\\u{cp:04x}")
        else:
            out.append(f"\\u{{{cp:x}}}")
    out.append('"')
    return "".join(out)


def write_generated(filename: str, body: str, generator: str) -> Path:
    """
    Write ``header(generator) + body`` to ``src/generated/<filename>`` with LF
    newlines and a single trailing newline. Returns the path written.
    """
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    path = GENERATED_DIR / filename
    content = header(generator) + body
    if not content.endswith("\n"):
        content += "\n"
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {path.relative_to(REPO_ROOT)} ({len(content)} bytes)")
    return path
